global.k[? 'up']   =global.profiles[#4+(global.profiles[#3,user]+1)*6+0,user]
global.k[? 'down'] =global.profiles[#4+(global.profiles[#3,user]+1)*6+1,user]
global.k[? 'left'] =global.profiles[#4+(global.profiles[#3,user]+1)*6+2,user]
global.k[? 'right']=global.profiles[#4+(global.profiles[#3,user]+1)*6+3,user]
global.k[? 'jump'] =global.profiles[#4+(global.profiles[#3,user]+1)*6+4,user]
global.k[? 'throw']=global.profiles[#4+(global.profiles[#3,user]+1)*6+5,user]
global.k[? 'dash'] =global.profiles[#4+(global.profiles[#3,user]+1)*6+6,user]
